---
title: "Bioinformatics Research Group"
output: html_document
---

<p> <a href="http://www.sdstate.edu/directory/xijin-ge">Dr. Xijin Ge</a> is an associate professor of bioinformatics at <a href="https://www.sdstate.edu/mathematics-statistics">Department of Mathematics and Statistics, South Dakota State University</a>. He teaches and conducts research in the general area of bioinformatics and computational biology. More about Dr. Ge's training and research can be found at <a href="https://scholar.google.com/citations?user=DFUSeDUAAAAJ&amp;hl=en">Google Scholar</a> and <a href="http://orcid.org/0000-0001-7406-3782">ORCiD</a>. <br><br> Currently, the main focus of his group is the role of transposable elements in the gene regulation, especially in embryonic stem cells. Another emphasis is the development of tools and resources for the interpretation of high-throughput genomics data. Dr. Ge also enjoys working with many collaborators in a supporting role. <br><br> We are also involved in teaching statistics and analytics to high school students as part of the education and outreach activities of <a href="http://sdepscor.org/">SD EPSCoR</a>. His research group is supported by <a href="http://www.nsf.gov/">National Science Foundation (NSF)</a>, <a href="http://www.nih.gov/">National Institutes of Health (NIH)</a>, the state of South Dakota, Sanford Health etc. <br> </p>
