---
title: "Publications"
output: html_document
---



> 1. Steven Xijin Ge, Exploratory bioinformatics analysis reveals importance of "junk" DNA in early embryo development  **bioRxiv2016** [Paper](http://biorxiv.org/content/biorxiv/early/2016/10/09/079921.full.pdf) [Abstract](http://biorxiv.org/content/early/2016/10/09/079921)
> 2. Liming Lai, Jason Hennessey, Valerie Bares, Eun Woo Son, Yuguang Ban, Wei Wang, Jianli Qi, Gaixin Jiang, Arthur Liberzon, Steven Ge, GSKB: A gene set database for pathway analysis in mouse  **bioRxiv** 082511 **2016** [Abstract](http://dx.doi.org/10.1101/082511) [Full text](http://biorxiv.org/content/biorxiv/early/2016/10/24/082511.full.pdf)
> 3. L Lai, X Ge, Meta-Analysis of Gene Expression Signatures Reveals Hidden Links among Diverse Biological Processes in Arabidopsis  **PLoS ONE**  9:e108567 **2014**
> 4. J Hennessey, X Ge, A cross disciplinary study of link decay and the effectiveness of mitigation techniques  **BMC bioinformatics** 14: S5 **2013**
> 5. MHT Ling, Y Ban, H Wen, SM Wang, X Ge, Conserved expression of natural antisense transcripts in mammals  **BMC Genomics** 14: 243 **2013**
> 6. MHT Ling, RC Rabara, P Tripathi, PJ Rushton, X Ge, Extending MapMan ontology to tobacco for visualization of gene expression  **Dataset Papers in Science** 2013:706465 **2013**
> 7. J Duan, J Shi, X Ge, L Dölken, W Moy, D He, S Shi, AR Sanders, J Ross, Genome-wide survey of interindividual differences of RNA stability in human lymphoblastoid cell lines  **Scientific Reports** 3:1318 **2013**
> 8. L Lai, A Liberzon, J Hennessey, G Jiang, J Qi, JP Mesirov, X Ge, AraPath: a knowledgebase for pathway analysis in Arabidopsis  **Bioinformatics** 28:2291-2292 **2012**
> 9. YF Chen, JV Pottala, NY Weltman, X Ge, OV Savinova, AM Gerdes, Regulation of gene expression with thyroid hormone in rats with myocardial infarction  **PLoS ONE** 7:e40161 **2012**
> 10. TJ Wilson, L Lai, Y Ban, XG Steven, Identification of metagenes and their interactions through large-scale analysis of Arabidopsis gene expression data  **BMC genomics** 13:237 **2012**
> 11. T Wilson, X Ge, ArraySearch: A Web-based Genomic Search Engine  **Comparative and Functional Genomics** 650842 **2012**
> 12.  XJ Ge, Large-scale analysis of expression signatures reveals hidden links among diverse cellular processes.  **BMC Systems Biology** 5:87 **2011** [Full text](https://firebasestorage.googleapis.com/v0/b/firebase-bcloud.appspot.com/o/Papers%2Flarge-scale.pdf?alt=media&token=16512d6c-623a-4d02-a68b-32c256b9838f) [BMC Highly Accessed](http://bmcsystbiol.biomedcentral.com/articles/10.1186/1752-0509-5-87)
> 13. Wang C, Chou CH, Tseng C, Ge X, Pinchuk LM., Early gene response of human brain microvascular endothelial cells to Listeria monocytogenes infection.  **Canadian J. Microbiology** 57:441-446 **2011** [Abstract](http://www.nrcresearchpress.com/doi/abs/10.1139/w11-018#.V9GprpMrKZM)
> 14. KA Graham, XJ Ge, A de Las Morenas, A Tripathi, CL Rosenberg, Gene expression profiles of estrogen receptor positive and estrogen receptor negative breast cancers are detectable in histologically normal epithelium  57:441-446 **2011** [Abstract](http://clincancerres.aacrjournals.org/content/early/2011/01/07/1078-0432.CCR-10-1369.abstract)
> 15. K Gedye, J Gonzalez-Hernandez, Y Ban, XJ Ge, J Thimmapuram, F Sun, C Wright, S Ali, A Boe, V Owens, Gene expression profiles of estrogen receptor positive and estrogen receptor negative breast cancers are detectable in histologically normal epithelium  57:441-446 **2011** [Full text](https://firebasestorage.googleapis.com/v0/b/firebase-bcloud.appspot.com/o/Papers%2Fprairie_cord_grass.pdf?alt=media&token=413f5a31-4a95-4d0c-94c0-98d59c2ef246)
> 16. L Shi et al., The MicroArray Quality Control (MAQC)-II study of common practices for the development and validation of microarray-based predictive models  28:827-38 **2010** [Abstract](http://europepmc.org/abstract/MED/20676074)
> 17. F Sutton, DG Chen, XJ Ge, D Kenefick, Gene expression profiles of estrogen receptor positive and estrogen receptor negative breast cancers are detectable in histologically normal epithelium  **BMC Plant Biology** 9:34 **2009** [Full text](https://firebasestorage.googleapis.com/v0/b/firebase-bcloud.appspot.com/o/Papers%2Fcbf_genes.pdf?alt=media&token=7e2cd48c-01c6-46b3-a54c-39d09f50fd70)
> 18. H Dong, XJ Ge, Y Shen, L Chen, Y Kong, H Zhang, X Man, L Tang, H Yuan, H Wang, G Zhao, W Jin., Gene expression profile analysis of human hepatocellular carcinoma using SAGE and LongSAGE  **BMC Med Genomics** 2:5 **2009** [Full text](https://firebasestorage.googleapis.com/v0/b/firebase-bcloud.appspot.com/o/Papers%2Fgene_exp_sage.pdf?alt=media&token=b386fca0-603c-457e-bcbb-0a4d0f684b02)
> 19. XJ Ge, WS Rubinstein, Y-C Jung, QF Wu, Genome-wide analysis of antisense transcription with Affymetrix exon array **BMC Genomics** 9:27 **2008** [Full text](https://firebasestorage.googleapis.com/v0/b/firebase-bcloud.appspot.com/o/Papers%2Fantisense_affymetrix.pdf?alt=media&token=8026ce42-7bf2-41d2-ac9c-175094715c5e) [(BMC Highly Accessed)](http://bmcgenomics.biomedcentral.com/articles/10.1186/1471-2164-9-27)
> 20. XJ Ge, QF Wu, SM Wang., SAGE detects microRNA precursors **BMC Genomics** 7:285 **2006** [Full text](https://firebasestorage.googleapis.com/v0/b/firebase-bcloud.appspot.com/o/Papers%2Fsage_mirna.pdf?alt=media&token=41def4dc-a67f-4761-bdd5-fe1dac14d791) [(BMC Highly Accessed)](http://bmcgenomics.biomedcentral.com/articles/10.1186/1471-2164-7-285)
> 21. XJ Ge, Q Wu, Y-C Jung, J Chen, SM Wang.  , A large quantity of novel human antisense transcripts detected by LongSAGE  **Bioinformatics** 22:2475-2479 **2006** [Full text](https://firebasestorage.googleapis.com/v0/b/firebase-bcloud.appspot.com/o/Papers%2Fnovel_human.pdf?alt=media&token=9c7f9e43-5f00-419e-a965-49473ed9e1b8) [(Thomson Scientific "New Hot Paper")](http://www.esi-topics.com/nhp/2008/january-08-Wang_Ge.html)
> 22. Y Guo, Y Chen, H Itoh, A Watanabe, XJ Ge, T Kodama, H Aburatani., Identification and characterization of lin-28 homolog B (LIN28B) in human hepatocellular carcinoma  **Gene** 384:51-61 **2006** [Abstract](http://www.sciencedirect.com/science/article/pii/S0378111906004446)
> 23. S Lee, J Chen, G Zhou, RZ Shi, G Bouffard, M Kocherginsky, XJ Ge, M Sun, N Jayathilaka, YC Kim, N Emmanuel,S Bohlander, M Minden, J Kline, O Ozer, R Larson, M LeBeau, E Green J Trent, T Karrison, P Liu, SM Wang, JD Rowley, Gene expression profiles in acute myeloid leukemia with common translocations using SAGE  **Proc. Nat. Acad. Sci. U.S.A.** 103:1030-1035 **2006** [Full text](https://firebasestorage.googleapis.com/v0/b/firebase-bcloud.appspot.com/o/Papers%2Fmyeloid_leuk.pdf?alt=media&token=30d858b3-3175-4908-93c9-c16525cabc7f) [(Thomson Scientific "New Hot Paper")](http://www.esi-topics.com/nhp/2008/january-08-Wang_Ge.html)
> 24. Y Chen, Y Guo, XJ Ge, H Itoh, A Watanabe, T Fujiwara, T Kodama, H Aburatani., Elevated expression and potential roles of human Sp5, a member of Sp transcription factor family, in human cancers  **Biochem. Biophys. Res. Commun** 340:758-766 **2006** [Abstract](http://www.sciencedirect.com/science/article/pii/S0006291X05027658)
> 25. XJ Ge, YC Jung, QF Wu, WA Kibbe, SM Wang, Annotating non-specific SAGE tags with microarray data  **Genomics** 87:173-180 **2006** [Abstract](http://www.sciencedirect.com/science/article/pii/S0888754305002454)
> 26. S Lee, D Johnson, K Dunbar, H Dong, XJ Ge, YC Kim, C Wing, N Jayathilaka, N Emmanuel, CQ Zhou, HL Gerber,CC Tseng, SM Wang, 2.45GHz radiofrequency fields alter gene expression in cultured human cells  **FEBS Lett.** 579:4829-4836 **2005** [Full text](https://firebasestorage.googleapis.com/v0/b/firebase-bcloud.appspot.com/o/Papers%2Fradiofrequency.pdf?alt=media&token=43eb2ef1-76e6-4dd8-8bfd-07288c9fd8b8)
> 27. XJ Ge, S Yamamoto, S Tsutsumi, Y Midorikawa, S Ihara, SM Wang, H Aburatani, Interpreting expression profiles of cancers by genome-wide survey of breadth of expression in normal tissues  **Genomics** 86:127-141 2005 [Full text](https://firebasestorage.googleapis.com/v0/b/firebase-bcloud.appspot.com/o/Papers%2Fexp_profiles_cancers.pdf?alt=media&token=728b1e43-a8c3-49c7-ae9d-1cdd3a51dd02) [Data](file:///Users/kruny1001/Desktop/www/www/index/papers/data/data2.html)
> 28. T Minami, K Horiuchi, M Miura, MR Abid, W Takabe, N Noguchi, T Kohro, XJ Ge, H Aburatani, T Hamakubo, T Kodama, WC Aird., Vascular endothelial growth factor- and thrombin-induced termination factor, Down syndrome critical region-1, attenuates endothelial cell proliferation and angiogenesis  **J. Biol. Chem.** 279:50537-50554 **2004** [Full text](https://firebasestorage.googleapis.com/v0/b/firebase-bcloud.appspot.com/o/Papers%2Fvascular_endo.pdf?alt=media&token=a6a2c300-99b4-4796-b20a-ba1e2dca045d) [(JBC "Paper of the Week")](http://www.jbc.org/content/279/48/e99925.full#FN1)
> 29. A Mukasa, K Ueki, XJ Ge, T Ide, T Fujimaki, R Nishikawa, A Asai, M Nakafuku, T Kirino & H Aburatani, Selective Expression of a Subset of Neuronal Genes in Oligodendroglioma with Chromosome 1p Loss  **Brain Pathology** 14:34-42 **2004** [Full text](https://firebasestorage.googleapis.com/v0/b/firebase-bcloud.appspot.com/o/Papers%2Foligodendroglioma.pdf?alt=media&token=07a41722-1b10-4e29-9e6a-1881b19969af)
> 30. XJ Ge, S Tsutsumi, S Iwata & H Aburatani, Reducing false positives in molecular pattern recognition.  **Genome Informatics** 14:34-43 **2003** [(The Best Paper Award) Full text](https://firebasestorage.googleapis.com/v0/b/firebase-bcloud.appspot.com/o/Papers%2Ffalse_positives.pdf?alt=media&token=6567e31b-47d8-4ec1-b1a8-05a287ba7bb0)
> 31. S Tsutsumi, T Taketani, K Nishimura, XJ Ge, T Taki, K Sugita, E Ishii, R Hanada, M Ohki, H Aburatani & Y Hayashi.  , Two distinct gene expression signatures in pediatric acute lymphoblastic leukemia with MLL rearrangements  **Cancer Res.** 63:4882-4887 **2003** [Full text](https://firebasestorage.googleapis.com/v0/b/firebase-bcloud.appspot.com/o/Papers%2Flymphoblastic_leuk.pdf?alt=media&token=87b08b5a-5c4b-451a-87e8-10a1e004ffb2)
> 32. XJ Ge, S Iwata., Learning the parts of objects by auto-association  **Neural Networks** 15:285-295 2002 [Full text](https://firebasestorage.googleapis.com/v0/b/firebase-bcloud.appspot.com/o/Papers%2Fauto-association.pdf?alt=media&token=b492e02a-bd29-48b5-a87f-4bf953ea7ab2)
> 33. XJ Ge, S Yonamine, YM Mi, S Tsutsumi, Y Kobune, H Aburatani, S Iwata, A physics-inspired algorithm for information visualization with application to gene expression analysis, Journal of The School of Engineering  **The University of Tokyo** XLVII:89-103 **2000**
> 34. XJ Ge, NX Chen, WQ Zhang, FW Zhu, Selective field evaporation in field-ion microscopy for ordered alloys  **J. of Applied Physics** 57:14203-14208 **1999**
> 35. NX Chen, XJ Ge, WQ Zhang, FW Zhu, Atomistic analysis of the field-ion microscopy image of Fe3Al  **Physical Review B-Condensed Matter** 57:14203-14208 **1998**
> 36. XJ Ge, NX Chen, ZD Chen, Efficient algorithms for 2D arithmetic Fourier transform  **IEEE Trans. on Signal Processing** 45:2136-2140 **1997**


